### ISSUE TITLE
Related to token and ID

### ISSUE THREAD

**Issue by shijuamt** [DiegoRBaquero/node-fb-messenger#15]
The token specified for sending msg is it Users token Right???
And ID is msg receivers id is it right?
But i got an error like this

Try Users token:

{ message: 'Unsupported post request. Object with ID \'me\' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api',
  type: 'GraphMethodException',
  code: 100,
  fbtrace_id: 'B69oYdvdIH3' }

Try page token I got this:

 Error:  { message: '(#100) No matching user found',
  type: 'OAuthException',
  code: 100,
  fbtrace_id: 'HBjp0Pu1DOb' }

Why i got this error??

**Comment by DiegoRBaquero** [comment]
The token is the page's token. The ID is the user's ID received in the webhook. 'me' won't work of course.

I invite you to read: https://developers.facebook.com/docs/messenger-platform
