### ISSUE TITLE
Typo in Documentation

### ISSUE THREAD

**Issue by machineghost** [DiegoRBaquero/node-fb-messenger#19]
This is really minor, but I thought you might want to fix:

> messenger.setPersistentMenu (pageId, menuItems[, cb]) // Set's Page's Persistent Meny

to instead be:

> messenger.setPersistentMenu (pageId, menuItems[, cb]) // Set's Page's Persistent Menu

(ie. "Menu" at the end, not "Meny").

**Comment by DiegoRBaquero** [comment]
Thanks!
