### ISSUE TITLE
[IMPORTANT] No updates for 0.0.x

### ISSUE THREAD

**Issue by DiegoRBaquero** [DiegoRBaquero/node-fb-messenger#2]
SemVer caret for 0.0.x releases doesn¡t allow updates at all.

I just bumped to 0.1.x to allow minor updates as SemVer treats 0.x.y as 0.major.minor from 0.1.0

Please update to 0.1.x manually or use `npm i --save fb-messenger@0.1` to get the latest version and receive the minor updates that will come soon!

Thank you

**Comment by andreafalzetti** [comment]
Thanks
