### ISSUE TITLE
Any way to access JSON sent to Facebook

### ISSUE THREAD

**Issue by machineghost** [DiegoRBaquero/node-fb-messenger#20]
I have a basic app that:
1. takes a message via a REST API
2. relays that message to Facebook Messenger using your wonderful library
3. returns a response via the same REST API

The problem I'm running in to is that in step 3 I'd like to return the JSON sent to Facebook Messenger, so that a QA script can hit my API and verify that the incoming message resulted in the correct outgoing message to Facebook ... but there is currently no way to access the request.  It's created inside the various send\* methods, then passed to `sendRequest` which sends it off to Facebook without exposing it in any way.

Could you please expose the request, or at least `req.json`?  It sees to me that the simplest way to do this would be to change line 187 from:

```
    cb(null, body);
```

to:

```
    cb(null, body, req);
```

However, that only gives you the request after the response comes back.  What would truly be ideal, in my opinion, is if `sendRequest` could simply return the `req`, and every send\* method returned the result of `sendRequest` ...

```
sendTextMessage (id, text, notificationType, cb) {
  const messageData = {
    text: text
  }
  return this.sendMessage(id, messageData, notificationType, cb)
}

const sendRequest = (req, cb) => {
  request(req, (err, res, body) => {
    if (!cb) return
    if (err) return cb(err)
    if (body.error) return cb(body.error)
    cb(null, body)
  })
  return req;
}
```

Could you please consider implementing one of these ways (or some alternative way) to expose the request object?

**Comment by DiegoRBaquero** [comment]
The request JSON is predictable as it's built with whatever you input as parameters to the functions. You can just recreate it:

``` js
var req = {
      url: 'https://graph.facebook.com/v2.6/me/messages',
      qs: {access_token: this.token},
      method: 'POST',
      json: {
        recipient: {
          id: id
        },
        message: 'XX'
        notifcation_type: ''REGULAR
      }
    }
```

Wouldn't that be enough? You can even wrap it.

**Comment by machineghost** [comment]
Sorry, I think the term "request JSON" has two meanings in this context.  I'm referring to `request.json`, not the JSON of the request itself.

The problem with that JSON is that if I do:

```
 sendImageMessage('foo', 'foo.png');
```

I have to essentially re-create your `sendImageMessage` method within my code to know that the resulting JSON will be:

```
{
  'attachment': {
    'type': 'image',
    'payload': {
      'url': 'foo.png'
    }
  }
}
```

I'd prefer not to do that, especially since I'd have to do so for every method in the library (essentially re-creating the entire library in my code).

Ideally instead I'd like to just access the above JSON somehow after it is generated.
