### ISSUE TITLE
Whitlisting domains

### ISSUE THREAD

**Issue by maxpastor** [DiegoRBaquero/node-fb-messenger#26]
When sending links in cards the link as to be on the page's whitelist for the message to be sent.
Can you add a method for that? Or validate my request if I find time to write it ?

**Comment by DiegoRBaquero** [comment]
I don't really understand, can you elaborate?

**Comment by maxpastor** [comment]
When you send a generic card (https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template), if one of your call to action is a link to a website, you have to send a request to facebook beforehand, that says that you approuved the domain.  https://developers.facebook.com/docs/messenger-platform/messenger-profile/domain-whitelisting

**Comment by maxpastor** [comment]
If you don't do this, facebook will response with a 500 when you try to send the generic card to the user because it found an unvalidated domain.

**Comment by DiegoRBaquero** [comment]
Ah, didn't know. Feel free to throw a PR :)
