### ISSUE TITLE
Any luck during sending list message?

### ISSUE THREAD

**Issue by DaniyalGeek** [DiegoRBaquero/node-fb-messenger#28]
i am trying to send with exact data  
.sendListMessage but no luck could you guide me or send me working one?

**Comment by DiegoRBaquero** [comment]
What's the actual issue or error?

I'm no longer maintaining the library.

**Comment by Tavernari** [comment]
For the issue is 

> TypeError: messenger.sendListMessage is not a function

**Comment by DiegoRBaquero** [comment]
Oh, it's because I haven't published latest code to npm.

1.2.0 is published now!

**Comment by Tavernari** [comment]
thanks a lot..

**Comment by DiegoRBaquero** [comment]
I've published 1.2.0 to npm :)
