### ISSUE TITLE
unsupported post request

### ISSUE THREAD

**Issue by denzils** [DiegoRBaquero/node-fb-messenger#32]
Permission for the User's Profile Information in a Messenger Bot should be implicitly granted "When a user begins a 1:1 thread with the bot for the first time".

My bot is still in sandbox mode (not sure if that is the issue), but with my own personal messenger account where I started the conversation with my bot -> my bot does not have access to my User Profile. It gets the following error:

{u'error': {u'message': u"Unsupported post request. Object with ID 'PAGE_SCOPED_USER_ID' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api", u'code': 100, u'type': u'GraphMethodException', u'fbtrace_id': u'Ev1G0M7KVxE', u'error_subcode': 33}}
Do you know why????

Thanks!

**Comment by DiegoRBaquero** [comment]
Keep in mind that the user id of facebook won't be the page scoped user id, users must start conversations first.

**Comment by denzils** [comment]
I'm confused -> I said with my personal account I did start the conversation first. Even after that, it still doesn't have access and I don't know how to grant access.

**Comment by DiegoRBaquero** [comment]
From the message the user sends to your bot, get the page scoped user id: `event.sender.id` and that should work
