### ISSUE TITLE
How to get the id of user <ID>

### ISSUE THREAD

**Issue by farrukhpl** [DiegoRBaquero/node-fb-messenger#33]
I am testing it. Token is the app page token but what is the id here?

**Comment by DiegoRBaquero** [comment]
When a user messages your bot, you receive it.

**Comment by farrukhpl** [comment]
Through Webhook ? So it is not possible to send message to user ,if user didn't text your bot once?
I don't know the flow, is it possible to send message from one user to other without the page involve as you know the token is of page. Will you please elaborate me the flow to use the messenger API. It is really important.

**Comment by DiegoRBaquero** [comment]
Correct

Diego
