### ISSUE TITLE
When I try to get Profile receiving error "Service temporarily unavailable"

### ISSUE THREAD

**Issue by Tavernari** [DiegoRBaquero/node-fb-messenger#36]
Hi,

Today I got a issue, every time  when I try to get profile I receive this erro "Service temporarily unavailable"

facebook error:  { message: '(#2) Service temporarily unavailable',
   type: 'OAuthException',
   is_transient: true,
   code: 2,
   fbtrace_id: 'H58BCfKkfuO' }

I don't know why.. but it happen every time

**Comment by Tavernari** [comment]
I found a Issue in Facebook Developer page saying about problem during the day. I will wait more update from facebook

**Comment by DiegoRBaquero** [comment]
Must have to do with FB, will close this. Re open if you encounter it again
