### ISSUE TITLE
what kind of format is <ID>

### ISSUE THREAD

**Issue by arpecop** [DiegoRBaquero/node-fb-messenger#5]
Hello, I've tried using my facebook-id and it returns :
Invalid fbid

**Comment by DiegoRBaquero** [comment]
> User IDs
> 
> With the pages_messaging permission, you can send messages to a person using their user id. These ids are sent to your webhook when a person comes through an entry point. Messages sent with this id will be delivered to a person's inbox.
> 
> These ids are page-scoped. These ids differ from those returned from Facebook Login apps which are app-scoped. You must use ids retrieved from a Messenger integration for this page in order to function properly.

From: https://developers.facebook.com/docs/messenger-platform/implementation#send_message

**Comment by arpecop** [comment]
before going any deeper using this feature may I ask is these ID's should be only for users "Liked" the page or any of APP user installed users?
Thanks

**Comment by DiegoRBaquero** [comment]
@arpecop Only users who have talked to the page through messenger and you've captured in your webhook.

**Comment by veb** [comment]
So basically developers who are part of the app/page, in this instance.

On Sun, Apr 24, 2016 at 12:46 PM, Diego Rodríguez Baquero <
notifications@github.com> wrote:

> @arpecop https://github.com/arpecop Only users who have talked to the
> page through messenger and you've captured in your webhook.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/DiegoRBaquero/node-fb-messenger/issues/5#issuecomment-213858452

## 

Mike Mackenzie, _BInfoTech_

http://veb.co.nz
Dunedin, New Zealand
